# bluedots-devops — Helm deploy orchestrator
#
# Deploy order: platform -> dpg -> aggregator-dpg
# All secrets + cloud outputs are sourced from a single file generated by
# opentofu (modules/output-file), passed to every helm command via `-f`.
#
# Run `make` (or `make help`) to see all targets.
# Run `make install` to deploy the full stack in order.

.DEFAULT_GOAL := help
SHELL := /bin/bash

COMMON_NS      ?= common-services
DPG_NS         ?= dpg
AGG_NS         ?= aggregator

COMMON_REL     ?= platform
DPG_REL        ?= dpg
AGG_REL        ?= aggregator

COMMON_DIR     := ./helm/common-services
DPG_DIR        := ./helm/signals
AGG_DIR        := ./helm/aggregator

GP3_SC_FILE    ?= ./opentofu/aws/template/gp3-sc.yaml

# Output file produced by `terragrunt run --all apply` on opentofu/aws/template.
# Override on the CLI:  make install CLOUD_VALUES=/path/to/global-cloud-values.yaml
CLOUD_VALUES   ?= ./opentofu/aws/dev/global-cloud-values.yaml

# Each helm chart is installed separately, so per-chart inputs are sliced out
# of the single CLOUD_VALUES file via yq. Slices land in this dir.
SLICE_DIR      := .helm-slices

# ─── help ──────────────────────────────────────────────────────────────────
help:  ## Show this help
	@awk 'BEGIN{FS=":.*##"; printf "\nUsage:\n  make \033[36m<target>\033[0m\n\nTargets:\n"} \
	      /^[a-zA-Z0-9_-]+:.*##/ {printf "  \033[36m%-22s\033[0m %s\n", $$1, $$2}' \
	      $(MAKEFILE_LIST)

# ─── preflight ─────────────────────────────────────────────────────────────
preflight:  ## Verify kubectl + helm + yq + cluster reachable + CLOUD_VALUES present
	@command -v helm    >/dev/null || { echo "ERROR: helm not installed";    exit 1; }
	@command -v kubectl >/dev/null || { echo "ERROR: kubectl not installed"; exit 1; }
	@command -v yq      >/dev/null || { echo "ERROR: yq (mikefarah) not installed"; exit 1; }
	@kubectl cluster-info >/dev/null 2>&1 || { echo "ERROR: cluster unreachable; check kubeconfig"; exit 1; }
	@test -f "$(CLOUD_VALUES)" || { \
	  echo "ERROR: $(CLOUD_VALUES) not found."; \
	  echo "       Run \`cd opentofu/aws/template && terragrunt run --all apply\` first,"; \
	  echo "       or override the path via  make ... CLOUD_VALUES=/abs/path/file.yaml"; \
	  exit 1; }
	@echo "context     : $$(kubectl config current-context)"
	@echo "cloud-values: $(CLOUD_VALUES)"

# Build a per-chart slice of CLOUD_VALUES. The chart's keys are at the root of
# CLOUD_VALUES under a wrapper named like the chart; we extract the wrapper
# subtree into $(SLICE_DIR)/<chart>.yaml so helm sees the values at root level.
$(SLICE_DIR)/%.yaml: $(CLOUD_VALUES) | $(SLICE_DIR)
	@# explode(.) dereferences YAML anchors INTO their alias sites before we
	@# project the subtree — otherwise sliced files reference anchors that
	@# live in default_passwords:/_irsa_service_account: blocks outside the
	@# projected subtree, and helm parser fails with "unknown anchor".
	@yq 'explode(.) | .["$*"]' $(CLOUD_VALUES) > $@.tmp
	@if [ "$$(cat $@.tmp)" = "null" ]; then \
	  echo "ERROR: $(CLOUD_VALUES) has no top-level key \"$*\""; \
	  rm -f $@.tmp; exit 1; \
	fi
	@mv $@.tmp $@

$(SLICE_DIR):
	@mkdir -p $(SLICE_DIR)

# ─── storage class ─────────────────────────────────────────────────────────
gp3-sc:  ## Apply gp3 StorageClass and make it cluster-default (strip gp2 default if present)
	@test -f "$(GP3_SC_FILE)" || { echo "ERROR: $(GP3_SC_FILE) not found"; exit 1; }
	kubectl apply -f $(GP3_SC_FILE)
	@if kubectl get sc gp2 >/dev/null 2>&1; then \
	  kubectl patch storageclass gp2 \
	    -p '{"metadata":{"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'; \
	fi
	@kubectl get sc

# ─── 1) platform ───────────────────────────────────────────────────────────
platform-install: preflight gp3-sc $(SLICE_DIR)/common-services.yaml  ## [1/3] Install common-services (ingress-nginx + cert-manager + ClusterIssuer + Postgres + Redis)
	helm upgrade --install $(COMMON_REL) $(COMMON_DIR) \
	  -n $(COMMON_NS) --create-namespace \
	  -f $(COMMON_DIR)/values.yaml \
	  -f $(SLICE_DIR)/common-services.yaml \
	  --wait --timeout 5m
	kubectl -n $(COMMON_NS) rollout status deploy/$(COMMON_REL)-ingress-nginx-controller --timeout=180s
	kubectl -n $(COMMON_NS) rollout status deploy/$(COMMON_REL)-cert-manager             --timeout=180s
	kubectl get clusterissuer letsencrypt-prod

platform-uninstall:  ## Uninstall platform release (cluster-wide impact)
	helm uninstall $(COMMON_REL) -n $(COMMON_NS) || true
	kubectl delete namespace $(COMMON_NS) --wait=true --timeout=120s || true

# ─── 2) dpg ────────────────────────────────────────────────────────────────
dpg-install: preflight $(SLICE_DIR)/signals.yaml  ## [2/3] Install DPG umbrella (api, ui, notification, match-score) — uses shared common-services DBs
	helm upgrade --install $(DPG_REL) $(DPG_DIR) \
	  -n $(DPG_NS) --create-namespace \
	  -f $(DPG_DIR)/values.yaml \
	  -f $(SLICE_DIR)/signals.yaml \
	  --wait --timeout 10m

dpg-cleanup:  ## Destroy DPG release + PVCs + namespace (DESTRUCTIVE)
	NAMESPACE=$(DPG_NS) RELEASE=$(DPG_REL) bash $(DPG_DIR)/install.sh cleanup --yes

# ─── 3) aggregator-dpg ─────────────────────────────────────────────────────
aggregator-install: preflight $(SLICE_DIR)/aggregator.yaml  ## [3/3] Install aggregator-dpg (web, api, worker, keycloak) — uses shared common-services DBs
	bash $(AGG_DIR)/install.sh -n $(AGG_NS) -r $(AGG_REL) \
	  -f $(SLICE_DIR)/aggregator.yaml

aggregator-uninstall:  ## Uninstall aggregator release
	helm uninstall $(AGG_REL) -n $(AGG_NS) || true
	kubectl delete namespace $(AGG_NS) --wait=true --timeout=120s || true

# ─── full stack ────────────────────────────────────────────────────────────
install: platform-install dpg-install aggregator-install  ## Install all 3 in order
	@echo
	@echo "✔ all releases deployed: platform, dpg, aggregator"
	@kubectl get clusterissuer letsencrypt-prod
	@kubectl -n $(DPG_NS) get pods,svc,ingress
	@kubectl -n $(AGG_NS) get pods,svc,ingress

uninstall: aggregator-uninstall dpg-cleanup platform-uninstall  ## Uninstall everything (reverse order)
	@echo "✔ all releases removed"

# ─── slice management ──────────────────────────────────────────────────────
slices: $(SLICE_DIR)/common-services.yaml $(SLICE_DIR)/signals.yaml $(SLICE_DIR)/aggregator.yaml  ## Regenerate all per-chart value slices from $(CLOUD_VALUES)
	@echo "✔ slices written under $(SLICE_DIR)/"

slices-clean:  ## Remove generated slices (next install will rebuild)
	rm -rf $(SLICE_DIR)

# ─── static checks ─────────────────────────────────────────────────────────
lint:  ## helm lint all 3 charts
	helm lint $(COMMON_DIR)
	helm lint $(DPG_DIR)
	helm lint $(AGG_DIR)

template:  ## helm template all 3 (rendering smoke test)
	@helm template $(COMMON_REL) $(COMMON_DIR)           >/dev/null && echo "✔ platform renders"
	@helm template $(DPG_REL)      $(DPG_DIR)                >/dev/null && echo "✔ dpg renders"
	@helm template $(AGG_REL)      $(AGG_DIR)                >/dev/null && echo "✔ aggregator-dpg renders"

dry-run: preflight slices  ## helm --dry-run all 3 against current cluster
	helm upgrade --install $(COMMON_REL) $(COMMON_DIR) -n $(COMMON_NS) --create-namespace \
	  -f $(COMMON_DIR)/values.yaml -f $(SLICE_DIR)/common-services.yaml --dry-run
	helm upgrade --install $(DPG_REL)    $(DPG_DIR)    -n $(DPG_NS)    --create-namespace \
	  -f $(DPG_DIR)/values.yaml    -f $(SLICE_DIR)/signals.yaml         --dry-run
	bash $(AGG_DIR)/install.sh -n $(AGG_NS) -r $(AGG_REL) -f $(SLICE_DIR)/aggregator.yaml --dry-run

.PHONY: help preflight gp3-sc \
        platform-install platform-uninstall \
        dpg-install dpg-cleanup \
        aggregator-install aggregator-uninstall \
        install uninstall slices slices-clean lint template dry-run
