variable "base_location" {
  description = "Absolute path of the terragrunt unit directory (used as the anchor for the generated yaml file location)"
  type        = string
}

variable "building_block" {
  description = "Naming prefix used for all resources"
  type        = string
}

variable "environment" {
  description = "Environment name"
  type        = string
}

variable "cloud_storage_provider" {
  description = "Cloud storage provider tag (e.g. aws)"
  type        = string
  default     = "aws"
}

variable "cloud_storage_region" {
  description = "AWS region for all resources"
  type        = string
}

variable "signals_host" {
  description = "FQDN for the signals API ingress (used as-is)"
  type        = string
  default     = "api.purpledots.servehalflife.com"
}

variable "signals_ui_host" {
  description = "FQDN for the signals UI ingress (used as-is)"
  type        = string
  default     = "purpledots.servehalflife.com"
}

variable "aggregator_host" {
  description = "FQDN for the aggregator public ingress (global.publicHost, used as-is)"
  type        = string
  default     = "aggregator.servehalflife.com"
}

# -----------------------------------------------------------------------------
# Network
# -----------------------------------------------------------------------------
variable "vpc_id" {
  type    = string
  default = ""
}

variable "vpc_cidr_block" {
  type    = string
  default = ""
}

variable "public_subnet_ids" {
  type    = list(string)
  default = []
}

variable "private_subnet_ids" {
  type    = list(string)
  default = []
}

variable "nat_gateway_public_ip" {
  type    = string
  default = ""
}

# -----------------------------------------------------------------------------
# EKS
# -----------------------------------------------------------------------------
variable "cluster_name" {
  type    = string
  default = ""
}

variable "cluster_endpoint" {
  type    = string
  default = ""
}

variable "cluster_arn" {
  type    = string
  default = ""
}

variable "oidc_provider_arn" {
  type    = string
  default = ""
}

variable "oidc_provider" {
  type    = string
  default = ""
}

variable "node_role_arn" {
  type    = string
  default = ""
}

variable "private_ingressgateway_ip" {
  type    = string
  default = ""
}

variable "cloudwatch_observability_role_arn" {
  type    = string
  default = ""
}

# -----------------------------------------------------------------------------
# IAM (IRSA)
# -----------------------------------------------------------------------------
variable "app_sa_role_arn" {
  type    = string
  default = ""
}

variable "app_sa_role_name" {
  type    = string
  default = ""
}

# -----------------------------------------------------------------------------
# Storage (S3)
# -----------------------------------------------------------------------------
variable "storage_bucket_public" {
  type    = string
  default = ""
}

variable "storage_bucket_private" {
  type    = string
  default = ""
}

# -----------------------------------------------------------------------------
# RDS (managed Postgres) — endpoint hostname from the rds module
# -----------------------------------------------------------------------------
variable "postgres_host" {
  description = "RDS endpoint hostname (no port). Replaces the in-cluster Postgres service FQDN in all three chart overlays."
  type        = string
  default     = ""
}

# -----------------------------------------------------------------------------
# Random secrets (generated by the random_passwords module)
# -----------------------------------------------------------------------------
variable "random_string" {
  type      = string
  sensitive = true
}

variable "encryption_string" {
  type      = string
  sensitive = true
  validation {
    condition     = length(var.encryption_string) == 32
    error_message = "encryption_string must be exactly 32 characters."
  }
}

variable "signalstack_admin_key" {
  type        = string
  sensitive   = true
  description = "Shared API key for aggregator.signalstackAdminKey and signals AGGREGATOR_DPG_API_KEY (same value, two consumers)"
}

# ─── Signals notification service ─────────────────────────────────────────
variable "notification_gmail_user" {
  type    = string
  default = ""
}

variable "notification_gmail_pass" {
  type      = string
  sensitive = true
  default   = ""
}

variable "notification_msg91_auth_key" {
  type      = string
  sensitive = true
  default   = ""
}

variable "notification_msg91_template_id" {
  type    = string
  default = ""
}

# ─── Aggregator mail ───────────────────────────────────────────────────────
variable "aggregator_smtp_user" {
  type    = string
  default = ""
}

variable "aggregator_smtp_password" {
  type      = string
  sensitive = true
  default   = ""
}

variable "aggregator_smtp_from" {
  type    = string
  default = ""
}

variable "aggregator_admin_emails" {
  type    = string
  default = ""
}

variable "aggregator_msg91_auth_key" {
  type      = string
  sensitive = true
  default   = ""
}

variable "aggregator_msg91_template_id" {
  type    = string
  default = ""
}

variable "signals_google_maps_api_key" {
  type    = string
  default = ""
}

# ─── Monitoring chart secrets ──────────────────────────────────────────────
variable "monitoring_grafana_password" {
  type      = string
  sensitive = true
}

variable "monitoring_email_enabled" {
  type        = bool
  default     = true
  description = "Enable email (SMTP) alert notifications"
}

variable "monitoring_smtp_host" {
  type        = string
  default     = "smtp.gmail.com:587"
  description = "SMTP server host:port for Alertmanager email notifications"
}

variable "monitoring_smtp_from" {
  type        = string
  default     = ""
  description = "Sender address for Alertmanager email notifications"
}

variable "monitoring_smtp_password" {
  type        = string
  sensitive   = true
  default     = ""
  description = "Gmail App Password for Alertmanager SMTP"
}

variable "monitoring_alert_email" {
  type        = string
  default     = ""
  description = "Recipient address for Alertmanager email notifications"
}

variable "monitoring_discord_enabled" {
  type        = bool
  default     = false
  description = "Enable Discord alert notifications (3 channels: critical, warning, info)"
}

variable "monitoring_discord_critical_webhook" {
  type        = string
  sensitive   = true
  default     = "https://discord.com/api/webhooks/CHANGE-ME/CHANGE-ME"
  description = "Discord webhook URL for the #alerts-critical channel"
}

variable "monitoring_discord_warning_webhook" {
  type        = string
  sensitive   = true
  default     = "https://discord.com/api/webhooks/CHANGE-ME/CHANGE-ME"
  description = "Discord webhook URL for the #alerts-warning channel"
}

variable "monitoring_discord_info_webhook" {
  type        = string
  sensitive   = true
  default     = "https://discord.com/api/webhooks/CHANGE-ME/CHANGE-ME"
  description = "Discord webhook URL for the #alerts-info (catch-all) channel"
}

# ─── Common-services (shared postgres+redis) ───────────────────────────────
variable "postgres_admin_password" {
  type      = string
  sensitive = true
}

# ─── Signals chart secrets ─────────────────────────────────────────────────
variable "signals_postgres_password" {
  type      = string
  sensitive = true
}

variable "signals_redis_password" {
  type      = string
  sensitive = true
}

variable "signals_auth_secret" {
  type      = string
  sensitive = true
}

variable "signals_pii_key" {
  type      = string
  sensitive = true
}

variable "signals_notification_secret" {
  type      = string
  sensitive = true
}

variable "signals_dpg_scoring_secret" {
  type      = string
  sensitive = true
}

# ─── Aggregator chart secrets ──────────────────────────────────────────────
variable "aggregator_postgres_password" {
  type      = string
  sensitive = true
}

variable "aggregator_kc_bootstrap_admin_password" {
  type      = string
  sensitive = true
}

variable "aggregator_keycloak_admin_client_secret" {
  type      = string
  sensitive = true
}

variable "aggregator_approval_token_secret" {
  type      = string
  sensitive = true
}

variable "aggregator_session_key" {
  type      = string
  sensitive = true
}

variable "aggregator_oidc_client_secret" {
  type      = string
  sensitive = true
}
