variable "base_location" {
  description = "Absolute path of the terragrunt unit directory (used as the anchor for the generated yaml file location)"
  type        = string
}

variable "building_block" {
  description = "Naming prefix used for all resources"
  type        = string
}

variable "environment" {
  description = "Environment name"
  type        = string
}

variable "cloud_storage_provider" {
  description = "Cloud storage provider tag (e.g. aws)"
  type        = string
  default     = "aws"
}

variable "cloud_storage_region" {
  description = "AWS region for all resources"
  type        = string
}

# ─── Signals hosts (host-routed served binding, PR #23) ─────────────────────
variable "signals_public_hosts" {
  description = "All FQDNs the signals release serves (UI + /api). The SOLE source of served hostnames: one host = single domain, several = multi-domain. No legacy single-host fallback."
  type        = list(string)

  validation {
    condition     = length(var.signals_public_hosts) > 0
    error_message = "signals_public_hosts must list at least one hostname (set it in global-values.yaml)."
  }
}

variable "signals_host_bindings" {
  description = "Host -> \"<network>/<domain>\" map for host-routed served binding. Empty = single-host mode (ui.hostBindings omitted entirely)."
  type        = string
  default     = ""
}

variable "signals_network" {
  description = "Network this cluster serves: drives NETWORK_CONFIG_LOCAL_FILE, the schema mount, and VITE_NETWORK_NAME."
  type        = string
  default     = "orange_dot"
}

variable "signals_allowed_origins" {
  description = "Precomputed CORS ALLOWED_ORIGINS (localhost dev + https://<each public host>)."
  type        = string
  default     = "http://localhost:8080,http://127.0.0.1:8080"
}

# -----------------------------------------------------------------------------
# Network
# -----------------------------------------------------------------------------
variable "vpc_id" {
  type    = string
  default = ""
}

variable "vpc_cidr_block" {
  type    = string
  default = ""
}

variable "public_subnet_ids" {
  type    = list(string)
  default = []
}

variable "private_subnet_ids" {
  type    = list(string)
  default = []
}

variable "nat_gateway_public_ip" {
  type    = string
  default = ""
}

# -----------------------------------------------------------------------------
# EKS
# -----------------------------------------------------------------------------
variable "cluster_name" {
  type    = string
  default = ""
}

variable "cluster_endpoint" {
  type    = string
  default = ""
}

variable "cluster_arn" {
  type    = string
  default = ""
}

variable "oidc_provider_arn" {
  type    = string
  default = ""
}

variable "oidc_provider" {
  type    = string
  default = ""
}

variable "node_role_arn" {
  type    = string
  default = ""
}

variable "private_ingressgateway_ip" {
  type    = string
  default = ""
}

variable "cloudwatch_observability_role_arn" {
  type    = string
  default = ""
}

# -----------------------------------------------------------------------------
# IAM (IRSA)
# -----------------------------------------------------------------------------
variable "app_sa_role_arn" {
  type    = string
  default = ""
}

variable "app_sa_role_name" {
  type    = string
  default = ""
}

# -----------------------------------------------------------------------------
# Storage (S3)
# -----------------------------------------------------------------------------
variable "storage_bucket_public" {
  type    = string
  default = ""
}

variable "storage_bucket_private" {
  type    = string
  default = ""
}

# -----------------------------------------------------------------------------
# Random secrets (generated by the random_passwords module)
# -----------------------------------------------------------------------------
variable "random_string" {
  type      = string
  sensitive = true
}

variable "encryption_string" {
  type      = string
  sensitive = true
  validation {
    condition     = length(var.encryption_string) == 32
    error_message = "encryption_string must be exactly 32 characters."
  }
}

variable "signalstack_admin_key" {
  type        = string
  sensitive   = true
  description = "Shared API key for aggregator.signalstackAdminKey and signals AGGREGATOR_DPG_API_KEY (same value, two consumers)"
}

# ─── Signals notification service ─────────────────────────────────────────
variable "notification_gmail_user" {
  type    = string
  default = ""
}

variable "notification_gmail_pass" {
  type      = string
  sensitive = true
  default   = ""
}

variable "notification_msg91_auth_key" {
  type      = string
  sensitive = true
  default   = ""
}

variable "notification_msg91_template_id" {
  type    = string
  default = ""
}

# ─── Aggregator mail ───────────────────────────────────────────────────────
variable "aggregator_smtp_user" {
  type    = string
  default = ""
}

variable "aggregator_smtp_password" {
  type      = string
  sensitive = true
  default   = ""
}

variable "aggregator_msg91_auth_key" {
  type      = string
  sensitive = true
  default   = ""
}

variable "signals_google_maps_api_key" {
  type    = string
  default = ""
}

# ─── Monitoring chart secrets ──────────────────────────────────────────────
variable "monitoring_grafana_password" {
  type      = string
  sensitive = true
}

# ─── Common-services (shared postgres+redis) ───────────────────────────────
variable "postgres_admin_password" {
  type      = string
  sensitive = true
}

# ─── Signals chart secrets ─────────────────────────────────────────────────
variable "signals_postgres_password" {
  type      = string
  sensitive = true
}

variable "signals_redis_password" {
  type      = string
  sensitive = true
}

variable "signals_auth_secret" {
  type      = string
  sensitive = true
}

variable "signals_pii_key" {
  type      = string
  sensitive = true
}

variable "signals_notification_secret" {
  type      = string
  sensitive = true
}

variable "signals_dpg_scoring_secret" {
  type      = string
  sensitive = true
}

# ─── Aggregator chart secrets ──────────────────────────────────────────────
variable "aggregator_postgres_password" {
  type      = string
  sensitive = true
}

variable "aggregator_kc_bootstrap_admin_password" {
  type      = string
  sensitive = true
}

variable "aggregator_keycloak_admin_client_secret" {
  type      = string
  sensitive = true
}

variable "aggregator_approval_token_secret" {
  type      = string
  sensitive = true
}

variable "aggregator_session_key" {
  type      = string
  sensitive = true
}

variable "aggregator_oidc_client_secret" {
  type      = string
  sensitive = true
}
