apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aggregator.fullname" . }}-keycloak-init
  labels:
    {{- include "aggregator.labels" . | nindent 4 }}
data:
  apply-user-profile.sh: |-
{{ .Files.Get "files/apply-user-profile.sh" | indent 4 }}
