{{- if .Values.dbInit.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "campaign-manager.fullname" . }}-dbinit
  labels:
    {{- include "campaign-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: dbinit
type: Opaque
stringData:
  PGPASSWORD: {{ required "database.admin.password is required" .Values.database.admin.password | quote }}
  MIGRATOR_PW: {{ required "database.migratorPassword is required" .Values.database.migratorPassword | quote }}
  APP_PW: {{ required "database.appPassword is required" .Values.database.appPassword | quote }}
  PIPELINE_PW: {{ required "database.pipelinePassword is required" .Values.database.pipelinePassword | quote }}
{{- end }}
