{{- if .Values.migrate.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "campaign-manager.fullname" . }}-migrate
  labels:
    {{- include "campaign-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: migrate
type: Opaque
stringData:
  MIGRATOR_DATABASE_URL: {{ include "campaign-manager.databaseUrl" (dict "db" .Values.database "user" "migrator" "password" .Values.database.migratorPassword "key" "database.migratorPassword") | quote }}
{{- end }}
