replicaCount: 1
image:
  repository: ghcr.io/huggingface/text-embeddings-inference
  tag: "cpu-1.7"
  pullPolicy: IfNotPresent
imagePullSecrets: []
embeddings:
  modelId: BAAI/bge-m3
  port: 80
reranker:
  enabled: true
  modelId: BAAI/bge-reranker-v2-m3
  port: 8081
resources:
  requests: { cpu: "1", memory: 2Gi }
  limits:   { cpu: "2", memory: 4Gi }
serviceAccount:
  create: true
