{{- $hpa := dict }}
{{- with .Values.global }}{{- with .aggregator }}{{- with .worker }}
  {{- if .hpa }}{{- $hpa = .hpa }}{{- end }}
{{- end }}{{- end }}{{- end }}
{{- if not $hpa }}{{- $hpa = .Values.hpa }}{{- end }}
{{- if $hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "worker.fullname" . }}
  labels:
    {{- include "worker.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "worker.fullname" . }}
  minReplicas: {{ $hpa.minReplicas }}
  maxReplicas: {{ $hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $hpa.targetCPU }}
{{- end }}
