{{- $pdb := dict }}
{{- with .Values.global }}{{- with .aggregator }}{{- with .worker }}
  {{- if .podDisruptionBudget }}{{- $pdb = .podDisruptionBudget }}{{- end }}
{{- end }}{{- end }}{{- end }}
{{- if not $pdb }}{{- $pdb = .Values.podDisruptionBudget }}{{- end }}
{{- if $pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "worker.fullname" . }}
  labels:
    {{- include "worker.labels" . | nindent 4 }}
spec:
  minAvailable: {{ $pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "worker.selectorLabels" . | nindent 6 }}
{{- end }}
