locals {
  global_cloud_values = {
    global = {
      building_block       = var.building_block
      environment          = var.environment
      cloud_storage_region = var.aws_region

      network = {
        vpc_id                 = var.network.vpc_id
        vpc_cidr_block         = var.network.vpc_cidr_block
        public_subnet_ids      = var.network.public_subnet_ids
        private_subnet_ids     = var.network.private_subnet_ids
        internet_gateway_id    = var.network.internet_gateway_id
        nat_gateway_id         = var.network.nat_gateway_id
        nat_gateway_public_ip  = var.network.nat_gateway_public_ip
        public_route_table_id  = var.network.public_route_table_id
        private_route_table_id = var.network.private_route_table_id
        security_group_id      = var.network.security_group_id
        subnets                = var.network.subnets
      }

      eks = {
        cluster_id                        = var.eks.cluster_id
        cluster_name                      = var.eks.cluster_name
        cluster_arn                       = var.eks.cluster_arn
        cluster_endpoint                  = var.eks.cluster_endpoint
        cluster_security_group_id         = var.eks.cluster_security_group_id
        oidc_provider_arn                 = var.eks.oidc_provider_arn
        oidc_provider                     = var.eks.oidc_provider
        node_role_arn                     = var.eks.node_role_arn
        private_lb_ip                     = var.eks.private_lb_ip
        cloudwatch_observability_role_arn = var.eks.cloudwatch_observability_role_arn
      }

      iam = {
        app_sa_role_arn  = var.iam.app_sa_role_arn
        app_sa_role_name = var.iam.app_sa_role_name
      }

      storage = {
        buckets                      = var.storage.buckets
        storage_bucket_public        = var.storage.storage_bucket_public
        storage_bucket_public_arn    = var.storage.storage_bucket_public_arn
        storage_bucket_public_domain = var.storage.storage_bucket_public_domain
        storage_bucket_private       = var.storage.storage_bucket_private
        storage_bucket_private_arn   = var.storage.storage_bucket_private_arn
        dial_bucket                  = var.storage.dial_bucket
        dial_bucket_arn              = var.storage.dial_bucket_arn
        velero_bucket                = var.storage.velero_bucket
        velero_bucket_arn            = var.storage.velero_bucket_arn
      }
    }
  }
}

resource "local_file" "global_cloud_values" {
  filename        = var.output_file_path
  file_permission = "0644"
  content = join("\n", [
    "# Auto-generated by the output module. Do not edit by hand.",
    "# Source: opentofu/aws/modules/output",
    yamlencode(local.global_cloud_values),
  ])
}
