apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak.envConfigMap" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
data:
  KC_DB: "postgres"
  KC_DB_URL: "jdbc:postgresql://{{ .Values.global.dataPlatform.postgresService }}.{{ .Values.global.dataPlatform.namespace }}.svc.cluster.local:5432/keycloak"
  KC_HOSTNAME: "{{ .Values.global.publicHost }}"
  KC_HOSTNAME_STRICT: "false"
  KC_HTTP_ENABLED: "true"
  KC_HEALTH_ENABLED: "true"
  KC_HTTP_RELATIVE_PATH: "/auth"
  KC_PROXY_HEADERS: "xforwarded"
  KC_BOOTSTRAP_ADMIN_USERNAME: "{{ .Values.bootstrapAdminUsername }}"
  PUBLIC_BASE_URL: "{{ include "keycloak.publicBaseUrl" . }}"
  KC_SPI_SMS_PROVIDER: "{{ .Values.smsProvider }}"
  MSG91_TEMPLATE_ID: "{{ .Values.msg91TemplateId }}"
  MSG91_OTP_VAR_NAME: "{{ .Values.msg91OtpVarName }}"
  AWS_REGION: "{{ .Values.awsRegion }}"
