{{- $autoscaling := dict }}
{{- with .Values.global }}{{- with .signals }}{{- with .api }}
  {{- if .autoscaling }}{{- $autoscaling = .autoscaling }}{{- end }}
{{- end }}{{- end }}{{- end }}
{{- if not $autoscaling }}{{- $autoscaling = .Values.autoscaling }}{{- end }}
{{- if $autoscaling.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "dpg-api.fullname" . }}
  labels:
    {{- include "dpg-api.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "dpg-api.fullname" . }}
  minReplicas: {{ $autoscaling.minReplicas }}
  maxReplicas: {{ $autoscaling.maxReplicas }}
  metrics:
    {{- if $autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if $autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
